---

name: lint-redoc
on:
  pull_request:
    types: [opened, reopened, synchronize]
run-name: ${{ github.workflow }} (${{ github.ref_name }})
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  redocly:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v4
      - name: Install redocly-cli
        run: npm install -g @redocly/cli
      - name: Bundle
        run: redocly bundle backend/storage/redoc/index.yaml -o backend/storage/redoc/openapi.yaml
      - name: Lint
        run: redocly lint backend/storage/redoc/openapi.yaml
