---

name: test-php
on:
  pull_request:
    types: [opened, reopened, synchronize]
run-name: ${{ github.workflow }} (${{ github.ref_name }})
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  contents: read
jobs:
  phpunit:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    defaults:
      run:
        working-directory: backend
    services:
      mysql:
        image: mysql:8.4
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
          MYSQL_USER: ci_user
          MYSQL_PASSWORD: ci_password
        options: >-
          --health-cmd "mysqladmin ping -h 127.0.0.1"
          --health-interval 20s
          --health-timeout 10s
          --health-retries 10
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
      - name: Composer install
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
      - name: Composer dump autoload
        run: composer dump-autoload
      - name: Decrypt .env
        run: php artisan env:decrypt --key=${{ secrets.ENV_CI_DECRYPT_KEY }} --force --env=ci --filename=.env
      - name: Generate key
        run: php artisan key:generate
      - name: Change directory permissions
        run: chmod -R 777 storage bootstrap/cache
      - name: Migrate
        run: php artisan migrate:refresh --seed --force
      - name: PHPUnit
        run: vendor/bin/phpunit
